# Generated by Django 2.0.7 on 2018-07-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicpage',
            old_name='description',
            new_name='summary',
        ),
    ]
