# Generated by Django 2.0.7 on 2018-07-20 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180720_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='bodysome',
            new_name='body',
        ),
    ]
