# Generated by Django 2.0.7 on 2018-07-20 21:42

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180720_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='next',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
