# Generated by Django 2.0.7 on 2018-07-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_homepage_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='test',
            field=models.TextField(blank=True),
        ),
    ]
