# Generated by Django 2.0.7 on 2018-07-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperpage',
            name='link',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
    ]
