# Generated by Django 2.0.7 on 2018-07-26 13:07

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_paperpage_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperpage',
            name='extensions',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('equation', wagtail.core.blocks.StructBlock([('equation_field', wagtail.core.blocks.TextBlock(required=True))])), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
    ]
